
import { db } from './server/db';
import { cachedEvents } from '@shared/schema';
import { desc, like, or } from 'drizzle-orm';

async function analyzeUntranslated() {
  console.log('🔍 ANALIZANDO EVENTOS CON POSIBLES TÉRMINOS EN INGLÉS...\n');
  
  // Common English terms that should be translated
  const englishTerms = [
    '%', 'Auction', 'Bill', 'Bond', 'Note', 'Rate', 'Index', 'Change', 
    'Speech', 'Report', 'Survey', 'Confidence', 'Sentiment', 'Climate',
    'Manufacturing', 'Services', 'Composite', 'Construction', 'Housing',
    'Sales', 'Orders', 'Production', 'Price', 'Prices', 'Cost', 'Costs',
    'Earnings', 'Employment', 'Unemployment', 'Jobless', 'Claims', 'Payroll',
    'Trade', 'Balance', 'Export', 'Import', 'Current', 'Account', 'Budget',
    'Deficit', 'Surplus', 'Gross', 'Domestic', 'Product', 'GDP', 'CPI', 'PPI',
    'PCE', 'YoY', 'MoM', 'QoQ', 'Year', 'Month', 'Quarter', 'Week', 'Day',
    'Fed', 'ECB', 'BoE', 'BoJ', 'RBA', 'RBNZ', 'BOC', 'SNB', 'FOMC',
    'Meeting', 'Minutes', 'Statement', 'Decision', 'Press', 'Conference',
    'Governor', 'Member', 'Chair', 'President', 'Treasury', 'Yield',
    'Mortgage', 'Application', 'Approval', 'Permit', 'Start', 'Existing',
    'New', 'Home', 'House', 'Store', 'Shop', 'Retail', 'Wholesale',
    'Business', 'Consumer', 'Industrial', 'Factory', 'Machine', 'Tool',
    'Vehicle', 'Car', 'Auto', 'Truck', 'Registration', 'Fuel', 'Oil',
    'Gas', 'Energy', 'Electricity', 'Power', 'Supply', 'Demand', 'Stock',
    'Inventory', 'Storage', 'Crude', 'Distillate', 'Gasoline', 'Heating',
    'Foreign', 'International', 'Global', 'Domestic', 'National', 'Regional',
    'State', 'Local', 'City', 'Urban', 'Rural', 'Farm', 'Non-Farm',
    'Private', 'Public', 'Government', 'Federal', 'Central', 'Bank',
    'Monetary', 'Fiscal', 'Policy', 'Economy', 'Economic', 'Financial',
    'Market', 'Exchange', 'Currency', 'Money', 'Credit', 'Debt', 'Loan',
    'Deposit', 'Reserve', 'Asset', 'Liability', 'Equity', 'Capital',
    'Investment', 'Spending', 'Consumption', 'Income', 'Wage', 'Salary',
    'Profit', 'Loss', 'Revenue', 'Tax', 'Duty', 'Tariff', 'Subsidy',
    'Welfare', 'Benefit', 'Pension', 'Insurance', 'Health', 'Education',
    'Transport', 'Communication', 'Technology', 'Innovation', 'Research',
    'Development', 'Science', 'Environment', 'Climate', 'Weather', 'Natural',
    'Resource', 'Mining', 'Agriculture', 'Fishing', 'Forestry', 'Hunting',
    'Real', 'Estate', 'Property', 'Land', 'Building', 'Construction',
    'Civil', 'Engineering', 'Architecture', 'Design', 'Art', 'Culture',
    'Entertainment', 'Recreation', 'Tourism', 'Travel', 'Hospitality',
    'Food', 'Beverage', 'Tobacco', 'Textile', 'Clothing', 'Footwear',
    'Leather', 'Paper', 'Printing', 'Publishing', 'Chemical', 'Pharmaceutical',
    'Plastic', 'Rubber', 'Metal', 'Mineral', 'Glass', 'Ceramic', 'Cement',
    'Concrete', 'Wood', 'Furniture', 'Electronic', 'Electrical', 'Equipment',
    'Computer', 'Software', 'Hardware', 'Internet', 'Telecommunication',
    'Broadcasting', 'Media', 'Advertising', 'Marketing', 'Consulting',
    'Legal', 'Accounting', 'Management', 'Administration', 'Support',
    'Waste', 'Water', 'Sewage', 'Sanitation', 'Recycling', 'Repair',
    'Maintenance', 'Installation', 'Cleaning', 'Security', 'Investigation',
    'Office', 'Administrative', 'Auxiliary', 'Activity', 'Service',
    'Household', 'Personal', 'Community', 'Social', 'Civic', 'Religious',
    'Political', 'Union', 'Association', 'Organization', 'Body', 'Authority',
    'Agency', 'Department', 'Ministry', 'Commission', 'Committee', 'Council',
    'Board', 'Panel', 'Group', 'Team', 'Force', 'Unit', 'Division',
    'Section', 'Branch', 'Office', 'Bureau', 'Agency', 'Center', 'Institute',
    'School', 'College', 'University', 'Academy', 'Foundation', 'Trust',
    'Fund', 'Charity', 'Non-Profit', 'NGO', 'IGO', 'MNC', 'SME', 'Start-up',
    'Enterprise', 'Company', 'Corporation', 'Partnership', 'Proprietorship',
    'Cooperative', 'Joint', 'Venture', 'Franchise', 'Subsidiary', 'Affiliate',
    'Holding', 'Conglomerate', 'Group', 'Consortium', 'Syndicate', 'Cartel',
    'Monopoly', 'Oligopoly', 'Competition', 'Regulation', 'Deregulation',
    'Privatization', 'Nationalization', 'Liberalization', 'Globalization',
    'Integration', 'Cooperation', 'Coordination', 'Harmonization', 'Standardization',
    'Certification', 'Accreditation', 'Inspection', 'Testing', 'Calibration',
    'Measurement', 'Metrology', 'Quality', 'Safety', 'Health', 'Environment',
    'Protection', 'Conservation', 'Preservation', 'Restoration', 'Rehabilitation',
    'Reconstruction', 'Development', 'Planning', 'Zoning', 'Land', 'Use',
    'Urban', 'Rural', 'Regional', 'Spatial', 'Territorial', 'Geography',
    'Demography', 'Population', 'Migration', 'Immigration', 'Emigration',
    'Refugee', 'Asylum', 'Citizenship', 'Nationality', 'Ethnicity', 'Race',
    'Gender', 'Age', 'Disability', 'Inequality', 'Poverty', 'Exclusion',
    'Inclusion', 'Diversity', 'Equality', 'Justice', 'Rights', 'Freedom',
    'Democracy', 'Governance', 'Corruption', 'Transparency', 'Accountability',
    'Responsibility', 'Ethics', 'Morality', 'Values', 'Norms', 'Culture',
    'Tradition', 'Custom', 'Habit', 'Behavior', 'Attitude', 'Opinion',
    'Belief', 'Religion', 'Faith', 'Spirituality', 'Ideology', 'Philosophy',
    'History', 'Heritage', 'Memory', 'Identity', 'Symbol', 'Language',
    'Communication', 'Information', 'Knowledge', 'Wisdom', 'Learning',
    'Education', 'Training', 'Skill', 'Competence', 'Talent', 'Creativity',
    'Innovation', 'Invention', 'Discovery', 'Research', 'Science', 'Technology',
    'Engineering', 'Mathematics', 'Logic', 'Reasoning', 'Analysis', 'Synthesis',
    'Evaluation', 'Assessment', 'Measurement', 'Statistics', 'Data', 'Information',
    'System', 'Network', 'Structure', 'Process', 'Function', 'Operation',
    'Management', 'Control', 'Regulation', 'Supervision', 'Monitoring',
    'Evaluation', 'Audit', 'Review', 'Report', 'Feedback', 'Improvement',
    'Change', 'Transformation', 'Transition', 'Reform', 'Revolution',
    'Evolution', 'Progress', 'Development', 'Growth', 'Expansion', 'Extension',
    'Diversification', 'Specialization', 'Concentration', 'Centralization',
    'Decentralization', 'Integration', 'Disintegration', 'Fragmentation',
    'Unification', 'Separation', 'Division', 'Partition', 'Distribution',
    'Allocation', 'Reallocation', 'Redistribution', 'Transfer', 'Exchange',
    'Transaction', 'Interaction', 'Relation', 'Relationship', 'Connection',
    'Link', 'Bond', 'Tie', 'Association', 'Affiliation', 'Membership',
    'Participation', 'Involvement', 'Engagement', 'Commitment', 'Contribution',
    'Support', 'Assistance', 'Aid', 'Help', 'Relief', 'Rescue', 'Recovery',
    'Reconstruction', 'Restoration', 'Rehabilitation', 'Renewal', 'Revival',
    'Resurgence', 'Renaissance', 'Rebirth', 'Regeneration', 'Reproduction',
    'Replication', 'Duplication', 'Imitation', 'Simulation', 'Model',
    'Prototype', 'Pilot', 'Experiment', 'Test', 'Trial', 'Demonstration',
    'Exhibition', 'Show', 'Fair', 'Festival', 'Event', 'Occasion',
    'Ceremony', 'Ritual', 'Celebration', 'Commemoration', 'Anniversary',
    'Jubilee', 'Centenary', 'Millennium', 'Holiday', 'Vacation', 'Leave',
    'Break', 'Rest', 'Relaxation', 'Leisure', 'Recreation', 'Entertainment',
    'Amusement', 'Fun', 'Play', 'Game', 'Sport', 'Exercise', 'Fitness',
    'Health', 'Wellness', 'Well-being', 'Happiness', 'Satisfaction',
    'Contentment', 'Joy', 'Pleasure', 'Delight', 'Excitement', 'Thrill',
    'Adventure', 'Challenge', 'Risk', 'Danger', 'Threat', 'Hazard',
    'Crisis', 'Emergency', 'Disaster', 'Catastrophe', 'Tragedy', 'Accident',
    'Incident', 'Event', 'Occurrence', 'Happening', 'Phenomenon', 'Situation',
    'Condition', 'State', 'Status', 'Position', 'Role', 'Function',
    'Purpose', 'Goal', 'Objective', 'Target', 'Aim', 'Ambition',
    'Aspiration', 'Desire', 'Wish', 'Hope', 'Dream', 'Vision',
    'Mission', 'Strategy', 'Tactic', 'Plan', 'Policy', 'Program',
    'Project', 'Scheme', 'Initiative', 'Action', 'Activity', 'Operation',
    'Task', 'Job', 'Work', 'Labor', 'Effort', 'Exertion', 'Struggle',
    'Conflict', 'Dispute', 'Controversy', 'Debate', 'Discussion', 'Dialogue',
    'Negotiation', 'Bargaining', 'Compromise', 'Agreement', 'Contract',
    'Treaty', 'Pact', 'Alliance', 'Coalition', 'Partnership', 'Cooperation',
    'Collaboration', 'Coordination', 'Integration', 'Unification', 'Union',
    'Merger', 'Acquisition', 'Takeover', 'Buyout', 'Investment', 'Divestment',
    'Spin-off', 'Split', 'Demerger', 'Restructuring', 'Reorganization',
    'Reform', 'Transformation', 'Change', 'Innovation', 'Modernization',
    'Development', 'Growth', 'Expansion', 'Extension', 'Diversification',
    'Specialization', 'Concentration', 'Centralization', 'Decentralization',
    'Globalization', 'Localization', 'Regionalization', 'Internationalization',
    'Transnationalization', 'Multinationalization', 'Supranationalization',
    'Intergovernmentalism', 'Federalism', 'Confederalism', 'Unitarianism',
    'Devolution', 'Autonomy', 'Independence', 'Sovereignty', 'Self-determination',
    'Democracy', 'Republic', 'Monarchy', 'Empire', 'Kingdom', 'Principality',
    'Duchy', 'County', 'Province', 'Region', 'District', 'Zone', 'Area',
    'Territory', 'Land', 'Country', 'Nation', 'State', 'People', 'Society',
    'Community', 'Population', 'Citizen', 'Resident', 'Inhabitant', 'Native',
    'Foreigner', 'Alien', 'Immigrant', 'Emigrant', 'Refugee', 'Asylum',
    'Seeker', 'Migrant', 'Worker', 'Employee', 'Employer', 'Manager',
    'Director', 'Executive', 'Officer', 'Official', 'Administrator',
    'Bureaucrat', 'Politician', 'Leader', 'Ruler', 'Monarch', 'President',
    'Minister', 'Secretary', 'Chancellor', 'Premier', 'Governor', 'Mayor',
    'Councilor', 'Representative', 'Delegate', 'Ambassador', 'Diplomat',
    'Envoy', 'Consul', 'Attache', 'Agent', 'Spy', 'Soldier', 'Warrior',
    'Fighter', 'Combatant', 'Veteran', 'Hero', 'Victim', 'Martyr',
    'Saint', 'Sinner', 'Criminal', 'Offender', 'Prisoner', 'Captive',
    'Hostage', 'Slave', 'Servant', 'Master', 'Lord', 'Lady', 'King',
    'Queen', 'Prince', 'Princess', 'Duke', 'Duchess', 'Earl', 'Countess',
    'Baron', 'Baroness', 'Knight', 'Dame', 'Squire', 'Page', 'Peasant',
    'Serf', 'Commoner', 'Citizen', 'Subject', 'Public', 'Masses', 'Crowd',
    'Mob', 'Group', 'Team', 'Gang', 'Band', 'Crew', 'Squad', 'Unit',
    'Force', 'Army', 'Navy', 'Air', 'Force', 'Marine', 'Corps', 'Guard',
    'Police', 'Constabulary', 'Sheriff', 'Marshal', 'Deputy', 'Officer',
    'Detective', 'Investigator', 'Inspector', 'Examiner', 'Auditor',
    'Controller', 'Regulator', 'Supervisor', 'Manager', 'Director',
    'Executive', 'Administrator', 'Leader', 'Head', 'Chief', 'Boss',
    'Owner', 'Proprietor', 'Shareholder', 'Stakeholder', 'Partner',
    'Associate', 'Colleague', 'Coworker', 'Peer', 'Friend', 'Ally',
    'Supporter', 'Follower', 'Fan', 'Admirer', 'Critic', 'Opponent',
    'Enemy', 'Rival', 'Competitor', 'Challenger', 'Contender', 'Candidate',
    'Applicant', 'Nominee', 'Appointee', 'Selectee', 'Designee', 'Successor',
    'Predecessor', 'Ancestor', 'Descendant', 'Parent', 'Child', 'Sibling',
    'Spouse', 'Partner', 'Relative', 'Family', 'Kin', 'Clan', 'Tribe',
    'Race', 'Ethnicity', 'Nation', 'People', 'Humanity', 'Mankind',
    'World', 'Earth', 'Planet', 'Universe', 'Cosmos', 'Nature', 'Environment',
    'Ecology', 'Biology', 'Life', 'Death', 'Birth', 'Growth', 'Decay',
    'Evolution', 'Creation', 'Destruction', 'Preservation', 'Conservation',
    'Protection', 'Defense', 'Security', 'Safety', 'Peace', 'War',
    'Conflict', 'Violence', 'Aggression', 'Attack', 'Assault', 'Invasion',
    'Occupation', 'Resistance', 'Rebellion', 'Revolution', 'Uprising',
    'Insurrection', 'Mutiny', 'Coup', 'Terrorism', 'Crime', 'Corruption',
    'Fraud', 'Theft', 'Robbery', 'Burglary', 'Murder', 'Homicide',
    'Manslaughter', 'Assassination', 'Execution', 'Suicide', 'Genocide',
    'Massacre', 'Atrocity', 'War', 'Crime', 'Human', 'Rights', 'Violation',
    'Abuse', 'Torture', 'Slavery', 'Trafficking', 'Exploitation', 'Oppression',
    'Persecution', 'Discrimination', 'Prejudice', 'Bigotry', 'Racism',
    'Sexism', 'Ageism', 'Classism', 'Nationalism', 'Patriotism', 'Chauvinism',
    'Jingoism', 'Xenophobia', 'Homophobia', 'Transphobia', 'Islamophobia',
    'Antisemitism', 'Hate', 'Speech', 'Crime', 'Violence', 'Harassment',
    'Bullying', 'Stalking', 'Intimidation', 'Coercion', 'Threat', 'Blackmail',
    'Extortion', 'Bribery', 'Graft', 'Embezzlement', 'Laundering', 'Smuggling',
    'Counterfeiting', 'Forgery', 'Piracy', 'Hacking', 'Cybercrime', 'Terrorism',
    'Espionage', 'Sabotage', 'Subversion', 'Treason', 'Sedition', 'Conspiracy',
    'Collusion', 'Complicity', 'Cover-up', 'Scandal', 'Controversy', 'Debate',
    'Argument', 'Dispute', 'Conflict', 'Struggle', 'Fight', 'Battle',
    'War', 'Campaign', 'Crusade', 'Movement', 'Cause', 'Mission',
    'Quest', 'Journey', 'Voyage', 'Expedition', 'Exploration', 'Discovery',
    'Invention', 'Innovation', 'Creation', 'Development', 'Progress',
    'Advancement', 'Improvement', 'Betterment', 'Enhancement', 'Enrichment',
    'Empowerment', 'Liberation', 'Emancipation', 'Freedom', 'Liberty',
    'Independence', 'Autonomy', 'Sovereignty', 'Self-determination', 'Democracy',
    'Republic', 'Constitution', 'Law', 'Justice', 'Right', 'Duty',
    'Obligation', 'Responsibility', 'Accountability', 'Transparency', 'Integrity',
    'Honesty', 'Truth', 'Fact', 'Reality', 'Knowledge', 'Wisdom',
    'Understanding', 'Insight', 'Perception', 'Awareness', 'Consciousness',
    'Mind', 'Soul', 'Spirit', 'Heart', 'Body', 'Health', 'Wellness',
    'Well-being', 'Happiness', 'Joy', 'Love', 'Peace', 'Harmony',
    'Balance', 'Order', 'Stability', 'Security', 'Safety', 'Protection',
    'Defense', 'Shelter', 'Home', 'Family', 'Community', 'Society',
    'Culture', 'Civilization', 'History', 'Heritage', 'Tradition', 'Custom',
    'Language', 'Art', 'Music', 'Literature', 'Science', 'Technology',
    'Industry', 'Economy', 'Politics', 'Religion', 'Philosophy', 'Ethics',
    'Morality', 'Values', 'Virtues', 'Principles', 'Standards', 'Norms',
    'Rules', 'Regulations', 'Laws', 'Policies', 'Strategies', 'Tactics',
    'Plans', 'Goals', 'Objectives', 'Targets', 'Aims', 'Ambitions',
    'Aspirations', 'Dreams', 'Visions', 'Hopes', 'Wishes', 'Desires',
    'Needs', 'Wants', 'Demands', 'Requirements', 'Expectations', 'Preferences',
    'Choices', 'Decisions', 'Actions', 'Behaviors', 'Habits', 'Routines',
    'Practices', 'Customs', 'Traditions', 'Rituals', 'Ceremonies', 'Celebrations',
    'Festivals', 'Holidays', 'Events', 'Occasions', 'Moments', 'Times',
    'Periods', 'Eras', 'Ages', 'Epochs', 'Generations', 'Lifetimes',
    'Centuries', 'Millennia', 'Eternity', 'Infinity', 'Space', 'Time',
    'Matter', 'Energy', 'Force', 'Power', 'Motion', 'Change',
    'Evolution', 'Revolution', 'Transformation', 'Transmutation', 'Metamorphosis',
    'Conversion', 'Adaptation', 'Adjustment', 'Modification', 'Alteration',
    'Variation', 'Deviation', 'Divergence', 'Convergence', 'Integration',
    'Disintegration', 'Fragmentation', 'Unification', 'Separation', 'Division',
    'Partition', 'Distribution', 'Allocation', 'Dispersion', 'Diffusion',
    'Spread', 'Expansion', 'Contraction', 'Growth', 'Decline', 'Rise',
    'Fall', 'Increase', 'Decrease', 'Gain', 'Loss', 'Profit',
    'Revenue', 'Income', 'Earnings', 'Wages', 'Salaries', 'Benefits',
    'Pensions', 'Dividends', 'Interest', 'Rent', 'Royalties', 'Fees',
    'Commissions', 'Bonuses', 'Incentives', 'Rewards', 'Prizes', 'Awards',
    'Honors', 'Titles', 'Degrees', 'Certificates', 'Diplomas', 'Licenses',
    'Permits', 'Visas', 'Passports', 'Documents', 'Records', 'Files',
    'Data', 'Information', 'Knowledge', 'Wisdom', 'Truth', 'Fact',
    'Reality', 'Fiction', 'Myth', 'Legend', 'Story', 'Tale',
    'Narrative', 'Account', 'Report', 'Description', 'Explanation', 'Interpretation',
    'Analysis', 'Evaluation', 'Assessment', 'Judgment', 'Opinion', 'View',
    'Perspective', 'Standpoint', 'Attitude', 'Belief', 'Faith', 'Trust',
    'Confidence', 'Doubt', 'Skepticism', 'Cynicism', 'Optimism', 'Pessimism',
    'Hope', 'Despair', 'Fear', 'Courage', 'Bravery', 'Heroism',
    'Cowardice', 'Weakness', 'Strength', 'Power', 'Authority', 'Influence',
    'Control', 'Dominance', 'Submission', 'Resistance', 'Rebellion', 'Revolution',
    'War', 'Peace', 'Love', 'Hate', 'Friendship', 'Enmity',
    'Alliance', 'Coalition', 'Partnership', 'Cooperation', 'Competition', 'Rivalry',
    'Conflict', 'Dispute', 'Argument', 'Debate', 'Discussion', 'Dialogue',
    'Conversation', 'Communication', 'Interaction', 'Relationship', 'Connection', 'Bond',
    'Tie', 'Link', 'Network', 'System', 'Structure', 'Organization',
    'Institution', 'Establishment', 'Foundation', 'Institute', 'Center', 'Agency',
    'Bureau', 'Office', 'Department', 'Ministry', 'Division', 'Section',
    'Branch', 'Unit', 'Group', 'Team', 'Force', 'Squad',
    'Crew', 'Band', 'Gang', 'Mob', 'Crowd', 'Mass',
    'Public', 'People', 'Nation', 'Country', 'State', 'Government',
    'Administration', 'Regime', 'Authority', 'Power', 'Rule', 'Law',
    'Order', 'Justice', 'Right', 'Freedom', 'Liberty', 'Equality',
    'Fraternity', 'Solidarity', 'Unity', 'Diversity', 'Inclusion', 'Exclusion',
    'Discrimination', 'Prejudice', 'Bias', 'Stereotype', 'Stigma', 'Taboo',
    'Norm', 'Value', 'Principle', 'Ideal', 'Standard', 'Criterion',
    'Measure', 'Indicator', 'Index', 'Rate', 'Ratio', 'Percentage',
    'Proportion', 'Fraction', 'Part', 'Whole', 'Total', 'Sum',
    'Aggregate', 'Average', 'Mean', 'Median', 'Mode', 'Range',
    'Variance', 'Deviation', 'Distribution', 'Frequency', 'Probability', 'Chance',
    'Risk', 'Uncertainty', 'Volatility', 'Stability', 'Equilibrium', 'Balance',
    'Harmony', 'Order', 'Chaos', 'Disorder', 'Confusion', 'Complexity',
    'Simplicity', 'Clarity', 'Ambiguity', 'Vagueness', 'Obscurity', 'Mystery',
    'Secret', 'Puzzle', 'Riddle', 'Problem', 'Question', 'Answer',
    'Solution', 'Resolution', 'Conclusion', 'Decision', 'Choice', 'Option',
    'Alternative', 'Possibility', 'Opportunity', 'Threat', 'Challenge', 'Difficulty',
    'Obstacle', 'Barrier', 'Hurdle', 'Limit', 'Constraint', 'Restriction',
    'Prohibition', 'Ban', 'Embargo', 'Sanction', 'Penalty', 'Punishment',
    'Fine', 'Sentence', 'Verdict', 'Judgment', 'Ruling', 'Decree',
    'Order', 'Command', 'Instruction', 'Direction', 'Guidance', 'Advice',
    'Suggestion', 'Recommendation', 'Proposal', 'Offer', 'Request', 'Demand',
    'Claim', 'Appeal', 'Petition', 'Application', 'Submission', 'Filing',
    'Registration', 'Enrollment', 'Admission', 'Entry', 'Access', 'Exit',
    'Departure', 'Arrival', 'Return', 'Stay', 'Visit', 'Journey',
    'Trip', 'Tour', 'Voyage', 'Expedition', 'Mission', 'Quest',
    'Adventure', 'Experience', 'Event', 'Occasion', 'Happening', 'Incident',
    'Accident', 'Disaster', 'Catastrophe', 'Tragedy', 'Comedy', 'Drama',
    'Story', 'Tale', 'Legend', 'Myth', 'Fable', 'Parable',
    'Allegory', 'Metaphor', 'Simile', 'Symbol', 'Sign', 'Signal',
    'Indication', 'Symptom', 'Manifestation', 'Expression', 'Representation', 'Depiction',
    'Portrayal', 'Image', 'Picture', 'Photograph', 'Painting', 'Drawing',
    'Sketch', 'Diagram', 'Chart', 'Graph', 'Map', 'Plan',
    'Design', 'Model', 'Pattern', 'Structure', 'Form', 'Shape',
    'Size', 'Dimension', 'Scale', 'Magnitude', 'Volume', 'Mass',
    'Weight', 'Density', 'Speed', 'Velocity', 'Acceleration', 'Momentum',
    'Force', 'Energy', 'Power', 'Work', 'Heat', 'Light',
    'Sound', 'Noise', 'Silence', 'Music', 'Rhythm', 'Melody',
    'Harmony', 'Tone', 'Pitch', 'Volume', 'Timbre', 'Color',
    'Hue', 'Saturation', 'Brightness', 'Contrast', 'Texture', 'Surface',
    'Material', 'Substance', 'Element', 'Compound', 'Mixture', 'Solution',
    'Fluid', 'Liquid', 'Gas', 'Solid', 'Plasma', 'Atom',
    'Molecule', 'Cell', 'Organism', 'Species', 'Genus', 'Family',
    'Order', 'Class', 'Phylum', 'Kingdom', 'Domain', 'Life',
    'Nature', 'Environment', 'Ecosystem', 'Habitat', 'Biosphere', 'Atmosphere',
    'Hydrosphere', 'Lithosphere', 'Geosphere', 'Universe', 'Cosmos', 'Space',
    'Time', 'Dimension', 'Reality', 'Existence', 'Being', 'Nothingness',
    'Void', 'Vacuum', 'Empty', 'Full', 'Whole', 'Part',
    'Piece', 'Fragment', 'Segment', 'Section', 'Portion', 'Share',
    'Slice', 'Chunk', 'Block', 'Bit', 'Byte', 'Word',
    'Sentence', 'Paragraph', 'Chapter', 'Book', 'Volume', 'Series',
    'Collection', 'Set', 'Group', 'Batch', 'Lot', 'Bundle',
    'Pack', 'Package', 'Container', 'Box', 'Case', 'Bag',
    'Sack', 'Pocket', 'Purse', 'Wallet', 'Safe', 'Vault',
    'Bank', 'Store', 'Shop', 'Market', 'Mall', 'Plaza',
    'Square', 'Street', 'Road', 'Avenue', 'Boulevard', 'Lane',
    'Alley', 'Path', 'Way', 'Route', 'Track', 'Trail',
    'Course', 'Direction', 'Orientation', 'Position', 'Location', 'Place',
    'Spot', 'Point', 'Site', 'Area', 'Region', 'Zone',
    'District', 'Neighborhood', 'Community', 'Town', 'City', 'Metropolis',
    'Capital', 'State', 'Province', 'Country', 'Nation', 'Continent',
    'World', 'Planet', 'Star', 'Galaxy', 'Universe', 'Cosmos'
  ];

  // Filter out very short words that might be false positives in Spanish (e.g. "No", "Si")
  const filteredTerms = englishTerms.filter(t => t.length > 2);

  const allEvents = await db.select().from(cachedEvents);
  const suspiciousEvents = [];

  for (const event of allEvents) {
    const spanishText = event.event;
    const englishText = event.eventOriginal;
    
    // Check if any English term is present in the Spanish text
    // We look for whole words to avoid partial matches inside Spanish words
    const foundTerms = filteredTerms.filter(term => {
      const regex = new RegExp(`\\b${term}\\b`, 'i');
      return regex.test(spanishText);
    });

    if (foundTerms.length > 0) {
      suspiciousEvents.push({
        id: event.id,
        spanish: spanishText,
        english: englishText,
        terms: foundTerms
      });
    }
  }

  console.log(`🔍 Encontrados ${suspiciousEvents.length} eventos con posibles términos en inglés.\n`);

  // Group by unique English text to avoid duplicates
  const uniqueSuspicious = new Map();
  suspiciousEvents.forEach(e => {
    if (!uniqueSuspicious.has(e.english)) {
      uniqueSuspicious.set(e.english, e);
    }
  });

  console.log(`📝 ${uniqueSuspicious.size} eventos únicos para revisar:\n`);

  let count = 0;
  for (const [english, data] of uniqueSuspicious) {
    if (count < 100) { // Limit output
      console.log(`🇬🇧 EN: "${english}"`);
      console.log(`🇪🇸 ES: "${data.spanish}"`);
      console.log(`⚠️  Terms: ${data.terms.join(', ')}`);
      console.log('-'.repeat(40));
      count++;
    }
  }

  if (uniqueSuspicious.size > 100) {
    console.log(`... y ${uniqueSuspicious.size - 100} más.`);
  }
  
  process.exit(0);
}

analyzeUntranslated();
